name: task_app
description: News app with clean architecture
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Networking
  dio: ^5.4.0
  # State Management
  flutter_bloc: ^8.1.3
  # Dependency Injection
  get_it: ^7.6.4
  # Functional Programming
  dartz: ^0.10.1
  # Equatable for comparison
  equatable: ^2.0.5
  # For caching
  shared_preferences: ^2.2.2
  # For internet check
  internet_connection_checker: ^1.0.0+1
  # For loading images
  cached_network_image: ^3.3.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true